### ISSUE TITLE
Possibility to get checked value/values of radio and checkbox components

### ISSUE THREAD

**Issue by deniszavadskiy** [mariomka/vue-checkbox-radio#1]
Hi, @mariomka , could you add possibility of getting checked value(radio) and checked values(checkbox) through emit on change them with event or another possible way? 
Smth like here http://vuejs.org/v2/guide/forms.html#Checkbox
Thanks.

**Comment by mariomka** [comment]
Definitely, it's a good suggestion.
I'll try to add it as soon as possible, today or tomorrow I hope.

**Comment by mariomka** [comment]
Done! Check out new v0.5.0 version.

Commit: bb3de47e64940fb3f38f5ce864a11fe7b6d518b0

**Comment by deniszavadskiy** [comment]
@mariomka Thanks a lot!
