### ISSUE TITLE
Some future requests

### ISSUE THREAD

**Issue by nickensoul** [mariomka/vue-checkbox-radio#2]
Thank you for this nice component! Very simple and useful.
But during working with it, I've found some things I'd like to see later:
1) Please, add slot supporting to the '.input-box' element.
For example, to include svg icon via 'use x-link'.
2) Sometimes we need to add a custom class name to the '.checkbox-component' element (parent tag), not only to the nested 'input'.
Thanks again!

**Comment by mariomka** [comment]
1. Yes, it can be useful. I can do in the next days but if you want to make a PR I agree.

2. Vue injects classes defined at the component in the root element, for example:

```html
<checkbox class="my-awesome-class">
Check me
</checkbox>
```

Renders to:

```html
<div class="checkbox-component my-awesome-class">
    [...]
</div>
```

I really appreciate ideas for improvement, thank you.

**Comment by nickensoul** [comment]
Thank you! I feel that you will do this faster than me.
Sorry for the 2nd point, really didn't know, that's cool!

**Comment by mariomka** [comment]
Slot ready! Check out https://github.com/mariomka/vue-checkbox-radio/commit/6a2c49090d56819d37ccff6779fc30daf712d7f9
