### ISSUE TITLE
checkbox doesn't work

### ISSUE THREAD

**Issue by appbeijing** [mariomka/vue-checkbox-radio#3]
<div class="formCon" v-if="item.type=='checkbox'">
				<label v-for="(option,index) in item.options"
					style="float:left; margin-right:20px;">
				<template  v-if="item.value==option.value">
					<checkbox 
						:name="item.name"
						:value="option.value"
						v-model="item.value"
						checked
					>
					   {{option.textvalue}}
					</checkbox>
				</template>

				<template v-else>
					<checkbox 
					:name="item.name"
					:value="option.value"
					v-model="item.value"
					>
					   {{option.textvalue}}
					</checkbox>
				</template>
				</label>
			</div>

**Comment by mariomka** [comment]
Can you provide a full example? Maybe a jsfiddle or codepen?
