### ISSUE TITLE
Allow boolean values

### ISSUE THREAD

**Issue by ghost** [mariomka/vue-checkbox-radio#4]
Using boolean values in radios currently yields a warning "Expected String, got Boolean".

It does work, but I think it'd be nice if the warning would be gone.

Use case: Building a switch with two radios. 

    <radio :value="true" v-model="doThing" checked>Do the thing</radio>
    <radio :value="false" v-model="doThing">Don't do the thing</radio>

(Yes, one could do this with a checkbox that's checked/unchecked, but that's not always practical depending on the labels used or when one wants the user to make a conscious decision to click something).

**Comment by mariomka** [comment]
Last version (v0.5.2) accepts booleans as values. I'm not sure if use booleans as values is the best idea but it's working.

By the way, as you are setting v-model you can set the default value instead of set checked attribute.

```js
data() {
  return {
    doThing: true,
  }
},
```

```html
<radio :value="true" v-model="doThing">Do the thing</radio>
<radio :value="false" v-model="doThing">Don't do the thing</radio>
```

**Comment by ghost** [comment]
Amazingly quick, thank you!
