### ISSUE TITLE
Radio groups: how can I know which of the radios was selected?

### ISSUE THREAD

**Issue by sergiocastrovale** [mariomka/vue-checkbox-radio#5]
I have something like this:

![screenshot_2](https://user-images.githubusercontent.com/8822036/31041461-c7920bec-a58d-11e7-8439-92531cec7794.png)

And this code:

```
<radio name="deal-type" @input="changeDealType(checked)">
    {{ dealType.description }}
</radio>
```

Is there any way I can tell _which_ of the radios on my radio group was checked? For all I can tell the @input emitted event only allows me to bring checked/unchecked status for this particular radio button, but I can't tell apart which one was clicked.

**Comment by mariomka** [comment]
You have some options:

- Use v-model and value properties (like in the demo).
- Access to original DOM element through $event: https://vuejs.org/v2/guide/events.html#Methods-in-Inline-Handlers
- Use value property that is returned on input event:
```js
<radio name="deal-type" value="one" @input="changeDealType">one<radio>
<radio name="deal-type" value="two" @input="changeDealType">two<radio>
```

**Comment by sergiocastrovale** [comment]
@mariomka thanks - ended up using the third method like this, inside a loop:

```
<radio name="deal-type" :checked="(dealType.id === selectedDealType.id)" :value="dealType.id + ''" @input="changeDealType">
    {{ dealType.description }}
</radio>
```

I had to tweak the _value_ a bit as it only accepts strings and I would be sending a Number but it does the job well.

**Comment by mariomka** [comment]
I'll remove type checking in `value` property, isn't helpful...
