### ISSUE TITLE
How to style checkbox and radio from outside

### ISSUE THREAD

**Issue by plashenkov** [mariomka/vue-checkbox-radio#7]
Here: https://mariomka.github.io/vue-checkbox-radio/ you are giving examples of how to style checkbox and radio components, but when I try to do that, my style is overridden by internal component style and thus does not have any effect.

How to solve or workaround this?

**Comment by mariomka** [comment]
I don't know why (each project, build system is different...) but a workaround can be using `class-name`to add a custom class.

**Comment by plashenkov** [comment]
Yeah, thank you. I've used `!important` as a workaround although this is not very beautiful.
