### ISSUE TITLE
event change 

### ISSUE THREAD

**Issue by orangeShadow** [mariomka/vue-checkbox-radio#9]
May be you can add change event ? Because sometimes you need do anything else.

**Comment by nickensoul** [comment]
[Here](https://github.com/mariomka/vue-checkbox-radio/blob/4c43dc49963b52accb36c662dc930a697706a30b/src/components/Checkbox.vue#L152) is the point we can pass an original event object.
Seems like I can do a PR for this, but I’d like to ask you, @orangeShadow, what did you meant by "anything else"?

**Comment by orangeShadow** [comment]
Yes, i solve my problem with input and bind, "anything else" was a constructor form, when I did't know what kind of element fire this event
